name = "lamalice25"
version = "0.0.1"
description = "A small example package"
readme = "RTFM.md"
Homepage = "https://github.com/lamalice25/tutobot-.git"
Issues = "https://github.com/pypa/sampleproject/issues"